//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITDb1Entities : DbContext
    {
        public ITDb1Entities()
            : base("name=ITDb1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_AllAns> Tbl_AllAns { get; set; }
        public DbSet<Tbl_Coordinator> Tbl_Coordinator { get; set; }
        public DbSet<tbl_CollgeLogin> tbl_CollgeLogin { get; set; }
        public DbSet<Tbl_Moderator> Tbl_Moderator { get; set; }
        public DbSet<Tbl_Code_Master> Tbl_Code_Master { get; set; }
        public DbSet<Tbl_Moderator_Marks> Tbl_Moderator_Marks { get; set; }
        public DbSet<Tbl_Marks> Tbl_Marks { get; set; }
        public DbSet<Tbl_Model_Ans_New> Tbl_Model_Ans_New { get; set; }
        public DbSet<bindPaper> bindPapers { get; set; }
        public DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public DbSet<Tbl_Decoded_Answer_Sheets> Tbl_Decoded_Answer_Sheets { get; set; }
        public DbSet<Tbl_Final_Ans> Tbl_Final_Ans { get; set; }
        public DbSet<TblAllAns_Bk> TblAllAns_Bk { get; set; }
        public DbSet<TblMarksBK> TblMarksBKs { get; set; }
        public DbSet<tbl_Teacher> tbl_Teacher { get; set; }
    }
}
