//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Teacher
    {
        public int ID { get; set; }
        public string IndexNo { get; set; }
        public string DivisionCode { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string MobileNo { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string SUB { get; set; }
    }
}
