//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AllAns
    {
        public int id { get; set; }
        public string TID { get; set; }
        public string PStatus { get; set; }
        public string IndexNo { get; set; }
        public string Seat_No { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Paper_ID { get; set; }
        public string Batch { get; set; }
        public string OS { get; set; }
        public string Q1Ans1 { get; set; }
        public string Q1Ans2 { get; set; }
        public string Q1Ans3 { get; set; }
        public string Q1Ans4 { get; set; }
        public string Q1Ans5 { get; set; }
        public string Q1Ans6 { get; set; }
        public string Q1Ans7 { get; set; }
        public string Q1Ans8 { get; set; }
        public string Q1Ans9 { get; set; }
        public string Q1Ans10 { get; set; }
        public string Q7Ans1 { get; set; }
        public string Q7Ans2 { get; set; }
        public string Q7Ans3 { get; set; }
        public string Q7Ans4 { get; set; }
        public string Q7Ans5 { get; set; }
        public string Q7Ans6 { get; set; }
        public string Q7Ans7 { get; set; }
        public string Q7Ans8 { get; set; }
        public string Q8Ans1 { get; set; }
        public string Q8Ans2 { get; set; }
        public string Q8Ans3 { get; set; }
        public string Q8Ans4 { get; set; }
        public string DivisionCode { get; set; }
        public string Stream { get; set; }
        public string IP { get; set; }
    }
}
