//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CollgeLogin
    {
        public int CID { get; set; }
        public string IndexNo { get; set; }
        public string Password { get; set; }
    }
}
