//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class Tbl_Model_Ans_New
    {
        public int ID { get; set; }
        public string Paper_ID { get; set; }
        public string Question_No { get; set; }
        public string Sub_Question { get; set; }
        public string Question { get; set; }
        public string Model_Ans { get; set; }
        public string Papers_Path { get; set; }
        public HttpPostedFileBase PaperID { get; set; }
    }
}
