//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Final_Ans
    {
        public int eid { get; set; }
        public string cstate { get; set; }
        public string seat_no { get; set; }
        public System.DateTime AssignedDatetime { get; set; }
        public string ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q1Ans1 { get; set; }
        public string Q1Ans2 { get; set; }
        public string Q1Ans3 { get; set; }
        public string Q1Ans4 { get; set; }
        public string Q1Ans5 { get; set; }
        public string Q1Ans6 { get; set; }
        public string Q1Ans7 { get; set; }
        public string Q1Ans8 { get; set; }
        public string Q1Ans9 { get; set; }
        public string Q1Ans10 { get; set; }
        public string Q2Ans1 { get; set; }
        public string Q2Ans2 { get; set; }
        public string Q2Ans3 { get; set; }
        public string Q2Ans4 { get; set; }
        public string Q2Ans5 { get; set; }
        public string Q2Ans6 { get; set; }
        public string Q2Ans7 { get; set; }
        public string Q2Ans8 { get; set; }
        public string Q2Ans9 { get; set; }
        public string Q2Ans10 { get; set; }
        public string Q3AAns1 { get; set; }
        public string Q3AAns2 { get; set; }
        public string Q3AAns3 { get; set; }
        public string Q3AAns4 { get; set; }
        public string Q3AAns5 { get; set; }
        public string Q3AAns6 { get; set; }
        public string Q3AAns7 { get; set; }
        public string Q3AAns8 { get; set; }
        public string Q3AAns9 { get; set; }
        public string Q3AAns10 { get; set; }
        public string Q3BAns11 { get; set; }
        public string Q3BAns12 { get; set; }
        public string Q3BAns13 { get; set; }
        public string Q3BAns14 { get; set; }
        public string Q3BAns15 { get; set; }
        public string Q3BAns16 { get; set; }
        public string Q3BAns17 { get; set; }
        public string Q3BAns18 { get; set; }
        public string Q3BAns19 { get; set; }
        public string Q3BAns20 { get; set; }
        public string Q4Ans1 { get; set; }
        public string Q4Ans2 { get; set; }
        public string Q4Ans3 { get; set; }
        public string Q4Ans4 { get; set; }
        public string Q4Ans5 { get; set; }
        public string Q5Ans1 { get; set; }
        public string Q5Ans2 { get; set; }
        public string Q6Ans1 { get; set; }
        public string Q6Ans2 { get; set; }
        public string Q7Ans1 { get; set; }
        public string Q7Ans2 { get; set; }
        public string Q7Ans3 { get; set; }
        public string Q7Ans4 { get; set; }
        public string Q7Ans5 { get; set; }
        public string Q7Ans6 { get; set; }
        public string Q7Ans7 { get; set; }
        public string Q7Ans8 { get; set; }
        public string Q8Ans1 { get; set; }
        public string Q8Ans2 { get; set; }
        public string Q8Ans3 { get; set; }
        public string Q8Ans4 { get; set; }
    }
}
