//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppITInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMarksBK
    {
        public int ID { get; set; }
        public string Seat_No { get; set; }
        public string Paper_ID { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<double> Q1Ans1 { get; set; }
        public Nullable<double> Q1Ans2 { get; set; }
        public Nullable<double> Q1Ans3 { get; set; }
        public Nullable<double> Q1Ans4 { get; set; }
        public Nullable<double> Q1Ans5 { get; set; }
        public Nullable<double> Q1Ans6 { get; set; }
        public Nullable<double> Q1Ans7 { get; set; }
        public Nullable<double> Q1Ans8 { get; set; }
        public Nullable<double> Q1Ans9 { get; set; }
        public Nullable<double> Q1Ans10 { get; set; }
        public Nullable<double> Q7Ans1 { get; set; }
        public Nullable<double> Q7Ans2 { get; set; }
        public Nullable<double> Q7Ans3 { get; set; }
        public Nullable<double> Q7Ans4 { get; set; }
        public Nullable<double> Q7Ans5 { get; set; }
        public Nullable<double> Q7Ans6 { get; set; }
        public Nullable<double> Q7Ans7 { get; set; }
        public Nullable<double> Q7Ans8 { get; set; }
        public Nullable<double> Q8Ans1 { get; set; }
        public Nullable<double> Q8Ans2 { get; set; }
        public Nullable<double> Q8Ans3 { get; set; }
        public Nullable<double> Q8Ans4 { get; set; }
    }
}
